#!/bin/bash

set -o errexit

EDITOR="${EDITOR:-vi}"
ZET_DIR="${ZET_DIR:-$HOME/zet}"


__git() {
    git -C "$ZET_DIR" "$@"
}

__is_initialized() {
    [ -d "$ZET_DIR" ]
    return $?
}

__check_init() {
    if ! __is_initialized; then
        echo "Zettelkasten repository has not been initiated. Run 'zet init' to do so."
        exit 1
    fi
}

x.init() {
    if __is_initialized; then
        echo "Zettelkasten already initialized. ($ZET_DIR)"
    else
        mkdir -p "$ZET_DIR"
        __git init
    fi

    # TODO: remote has to be properly configured.
}

x.new() {
    __check_init

    local zet_id="$(gdate +"%Y%m%d%H%M%S%3N")"
    local zet_folder="$ZET_DIR/$zet_id"
    local zet_file="$zet_folder/README.md"

    mkdir -p "$zet_folder"
    touch "$zet_file"
    echo "---" >> "$zet_file"
    echo "id: $zet_id" >> "$zet_file"
    echo "tags: []" >> "$zet_file"
    echo "---" >> "$zet_file"

    exec "$EDITOR" "$zet_file"
}

# TODO: cache for tag research? files with indexes for each tag that can be
# used for searching, or refreshed.

x.tags() {
    __check_init
}

x.search() {
    __check_init
}

x.sync() {
    __check_init

    __git status --short
    __git add --all
    __git commit --verbose
    __git push
}

case "$1" in
    new) shift ; x.new "$@" ;;
    init) shift ; x.init "$@" ;;
    sync) shift ; x.sync "$@" ;;
    *) echo "Unknown command '$1'" ; exit 1 ;;
esac
